### ISSUE TITLE
ASAP and metapopulation examples don't work

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-fish-tools/r4MAS#49]
Hello @msupernaw ,

The ASAP and metapopulation examples don't work after installing the latest r4MAS (2b44c77d3c77f51ed52c6cf41a3afd7f94c67724). R stops working after `mas_model$Run()` but it still works after installing this version of r4MAS (3d1a58fd42be8f12c4d033b94bcb146431e60e84). Let me know if you have any thoughts or suggestions!

**Comment by msupernaw** [comment]
Hello @Bai-Li-NOAA ,

We broke something when we cleaned out the repo. The package doesn't load properly!

**Comment by Bai-Li-NOAA** [comment]
The two examples work now. I will close this issue.
